### ISSUE TITLE
zlib.error

### ISSUE THREAD

**Issue by v01tag3** [axcheron/ptexplorer#1]
Good day!
I'm try to convert simple pkt file and get error:

```
python3 ~/bin/test.py -d ~/Downloads/2245.pkt  ~/22
[*] Opening Packet Tracer file '/home/v0ltage/Downloads/2245.pkt'
[*] File size compressed = 42134 bytes
[*] File size uncompressed = 2950562400 bytes
[*] Writing XML to '/home/v0ltage/22'
Traceback (most recent call last):
  File "/home/v0ltage/bin/test.py", line 81, in <module>
    ptfile_decode(args.infile, args.outfile)
  File "/home/v0ltage/bin/test.py", line 34, in ptfile_decode
    f.write(zlib.decompress(out[4:]))
zlib.error: Error -3 while decompressing data: incorrect header check
```
How can I overcome it?
[example of file](https://yadi.sk/d/q1YSpZ9qxqR_9Q)

**Comment by finax-1** [comment]
Same problem here, tried with an older file (Version ~5) and it worked... seems like they have changed the algorithm (maybe something with the first 4 bytes??)

**Comment by kaiffeetasse** [comment]
same here, is it possible to "convert" a newer pka file to an older format?

**Comment by v01tag3** [comment]
I'm think, there no special converter from new PT to old. Old version of PT not supporting files that was created on new version.  May be there is a way to pull the decoder from the client Cisco PT?

**Comment by axcheron** [comment]
Indeed, this is a version issue. It should works with PKA/PKT version 5 (or so). But it does NOT work with newer versions. I'll need some time to reverse the newer versions... sorry about that.
